Use CS306 as the builder for GitHub Workflow CI/CD

diff --git a/scripts/with-builder b/scripts/with-builder
--- a/scripts/with-builder
+++ b/scripts/with-builder
@@ -7,14 +7,19 @@ main() {
 	local builderMachine="$1"
 	local args=( "${@:2}" )
 
-	if ! addr=$(ip::find "$builderMachine"); then
-		echo "Could not find IP for server '$builderMachine'" >&2
-		exit 1
-	fi
+	if [[ "$builderMachine" == "" ]]; then
+		echo "No builder machine specified, not using a builder" >&2
+	else
+		if ! addr=$(ip::find "$builderMachine"); then
+			echo "Could not find IP for server '$builderMachine'" >&2
+			exit 1
+		fi
 
-	export NIX_CONFIG NIX_SSH_OPTS
-	NIX_CONFIG="builders = ssh://$addr"
-	NIX_SSH_OPTS="-i $(lib::root_path secrets/ssh/id_ed25519)"
+		echo "Using builder machine via SSH at $addr" >&2
+		export NIX_CONFIG NIX_SSH_OPTS
+		NIX_CONFIG="builders = ssh://$addr"
+		NIX_SSH_OPTS="-i $(lib::root_path secrets/ssh/id_ed25519)"
+	fi
 
 	"${args[@]}"
 }
